### ISSUE TITLE
grub-protect gets not compiled

### ISSUE THREAD

**Issue by hamtam1** [lcp/grub2#1]
I checked out tpm2-unlock-authpol-v1-wip and I was able to compile it. But when I tried to test tpm2 I found that grub-protect was not compiled.
Thank you for implementing all this.

**Comment by lcp** [comment]
grub-protect is currently exclusive for the EFI build. Be sure to enable EFI platform with "./configure --with-platform=efi".

**Comment by hamtam1** [comment]
okay now it gets compiled. I want to test it with coreboot. But first I will test it with UEFI and in future also with coreboot.
